[build]
  command = 'npm run build'
  functions = "functions"
  publish = 'build'
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/highscore/*"
  status = 200
  to = "/.netlify/functions/highscore/:splat"